### ISSUE TITLE
Recursively apply to directories

### ISSUE THREAD

**Issue by petrem** [MarcoGorelli/auto-walrus#17]
It would be slightly useful to allow the tool to take directories and apply the changes recursively to all *.py files.
Not that you couldn't `find . -name \*.py -exec auto-walrus --line-length 88 '{}' \;` or something.

Would you see this as a desirable feature? If so (without signing any promise in blood), I would try to write a PR.

**Comment by MarcoGorelli** [comment]
sorry, I only accept feature requests if accompanied by blood promises

**Comment by petrem** [comment]
ok `cross(self.heart) && hope(sys.exit())`...?

**Comment by MarcoGorelli** [comment]
I'd accept a PR, although I'm a little surprised that anyone is actually using this package, it was intended as more of a joke than anything 😄

**Comment by MarcoGorelli** [comment]
could you check how cython-lint does it please? we can reuse the same config from there

**Comment by baseplate-admin** [comment]
Hi uh, is this fixed?

I think 
* #19  

Fixes the issue but it's not on PyPi?

**Comment by MarcoGorelli** [comment]
Sorry about that, I'll make a release now
