### ISSUE TITLE
Feature request: Possibility to ignore specific lines of codes

### ISSUE THREAD

**Issue by DmytroLitvinov** [MarcoGorelli/auto-walrus#3]
Hi there.

Thanks a lot for that code-formatter. Just want to leave here a feature request about ignoring the specific lines of codes where it should not be applied. Would you be interested in seeing that feature in that package? Do you need help with developing it? Appreciate any thoughts around that feature-request. Thanks in advance.

**Comment by MarcoGorelli** [comment]
hey - like, a `# no-walrus` command? so, if either the assignment (`n = 10  # no-walrus`) or the if-statement (`if n > 3:  # no-walrus`) contain the comment, then don't rewrite?

sounds good to me, would welcome a pull request!

**Comment by MarcoGorelli** [comment]
should be available as of version 0.1.7, thanks @DmytroLitvinov for your request, and Слава Україні!

**Comment by DmytroLitvinov** [comment]
Thanks a lot for so fast response and so quick implementation.

Героям слава! 🇺🇦
