### ISSUE TITLE
`pipx run auto-walrus` no longer works with v0.3.2

### ISSUE THREAD

**Issue by cclauss** [MarcoGorelli/auto-walrus#33]
https://pipx.pypa.io
https://github.com/MarcoGorelli/auto-walrus/releases

% `pipx run auto-walrus`
> 'auto-walrus' executable script not found in package 'auto-walrus'.
Available executable scripts:

**Comment by MarcoGorelli** [comment]
oops thanks, just pushed a new release

**Comment by MarcoGorelli** [comment]
thanks for the quick report, really appreciate it 🙏
