### ISSUE TITLE
risky to auto-walrus into while statements

### ISSUE THREAD

**Issue by eriknw** [MarcoGorelli/auto-walrus#5]
For example, changing
```python
    i = 10
    while i > 0:
        i -= 1
```
to
```python
    while (i := 10) > 0:
        i -= 1
```
is probably not desirable, since the latter never completes.

**Comment by MarcoGorelli** [comment]
thanks @eriknw , that's a very good point

not sure what (if anything?) can be done to detect when it's safe or not to rewrite while loops, so I'll remove it

**Comment by MarcoGorelli** [comment]
done in version 0.1.8

**Comment by eriknw** [comment]
Very fast, thanks :tada:  (also, neat library :) )
